apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      dnsPolicy: ClusterFirst
      # ADD THIS BLOCK: Runs migrations before spinning up the main container
      { { - if .Values.migrationCommand } }
      initContainers:
        - name: { { .Values.appName } }-migration
          image: { { .Values.image } }
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args:
            - { { .Values.migrationCommand } }
          { { - if .Values.env } }
          env:
            { { - toYaml .Values.env | nindent 10 } }
          { { - end } }
      { { - end } }

      containers:
        - name: { { .Values.appName } }-container
          image: { { .Values.image } }
          imagePullPolicy: Always
          ports:
            - containerPort: { { .Values.containerPort } }
              hostPort: { { .Values.hostPort } }
          { { - if .Values.env } }
          env:
            { { - toYaml .Values.env | nindent 8 } }
          { { - end } }