apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.hostPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}